version: '3'

services:
  db:
    container_name: fsms-db
    image: postgres:alpine
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "fsms"
      POSTGRES_USER: "fsms"
      POSTGRES_PASSWORD: "password"
    ports:
      - "15432:5432"
