version: '3'

services:
  db:
    image: postgres:alpine
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "fsms"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
